version : "2.1"
services:
  db:
    image: mysql:5.6
    container_name: docker-mysql
    restart: always
    ports:
       - "3306:3306"
    restart: always
    networks:
      - microservicesnet
    volumes:
        -  ./init_schema:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: test

  eureka:
    image: hiteshjoshi1/microservice-docker-cart-example
    container_name: eureka
    hostname: eureka
    ports:
      - "1111:1111"
    networks:
      - microservicesnet
    volumes:
      - ${HOME}/jarloc:/data
    command: -jar -Dspring.profiles.active=docker /data/servicediscovery-0.0.1-SNAPSHOT.jar
    healthcheck:
      test: curl --fail -s http://localhost:1111/info || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3 
  

  config:
    image: hiteshjoshi1/microservice-docker-cart-example
    container_name: config
    hostname: config
    ports:
       - "5555:5555"
    networks:
      - microservicesnet
    volumes:
      - ${HOME}/jarloc:/data
    command: -jar -Dspring.profiles.active=docker /data/config-0.0.1-SNAPSHOT.jar
    depends_on:
       eureka:
         condition: service_healthy 
    healthcheck:
      test: curl --fail -s http://localhost:5555/info || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3 


  customer1:
    image: hiteshjoshi1/microservice-docker-cart-example
    container_name: customer1
    ports:
     - "2222:2222"
    networks:
      - microservicesnet
    volumes:
      - ${HOME}/jarloc:/data
    command: -jar -Dspring.profiles.active=docker -Dspring.datasource.url=jdbc:mysql://docker-mysql/microservices_cust -Dspring.datasource.password=test /data/customer-0.0.1-SNAPSHOT.jar
    depends_on:
       db:
         condition: service_started
       config:
         condition: service_healthy
       invoice1:
         condition: service_started  

  inventory1:
    image: hiteshjoshi1/microservice-docker-cart-example
    container_name: inventory1
    ports:
     - "3333:3333"
    networks:
      - microservicesnet
    volumes:
      - ${HOME}/jarloc:/data
    command: -jar -Dspring.profiles.active=docker -Dspring.datasource.url=jdbc:mysql://docker-mysql/microservices_prod -Dspring.datasource.password=test /data/inventory-0.0.1-SNAPSHOT.jar
    depends_on:
       db:
         condition: service_started
       config:
         condition: service_healthy

  invoice1:
    image: hiteshjoshi1/microservice-docker-cart-example
    container_name: invoice1
    ports:
     - "4444:4444"
    networks:
      - microservicesnet
    volumes:
      - ${HOME}/jarloc:/data
    command: -jar -Dspring.profiles.active=docker -Dspring.datasource.url=jdbc:mysql://docker-mysql/microservices_invoice -Dspring.datasource.password=test /data/invoice-0.0.1-SNAPSHOT.jar
    depends_on:
       db:
         condition: service_started
       config:
         condition: service_healthy
         
  # monitor:
  #   image: hiteshjoshi1/microservice-docker-cart-example
  #   container_name: monitor
  #   ports:
  #    - "7777:7777"
  #   networks:
  #     - microservicesnet
  #   volumes:
  #     - ${HOME}/jarloc:/data
  #   command: -jar -Dspring.profiles.active=docker -Dspring.datasource.url=jdbc:mysql://docker-mysql/microservices_invoice -Dspring.datasource.password=test /data/monitor-0.0.1-SNAPSHOT.jar
  #   depends_on:
  #      db:
  #        condition: service_started
  #      config:
  #        condition: service_healthy
  #      customer1:
  #        condition: service_started 

  zuul:
    image: hiteshjoshi1/microservice-docker-cart-example
    container_name: zuul
    ports:
     - "1101:1101"
    networks:
      - microservicesnet
    volumes:
      - ${HOME}/jarloc:/data
    command: -jar -Dspring.profiles.active=docker /data/zuulEdgeGateway-0.0.1-SNAPSHOT.jar
    depends_on:
       config:
         condition: service_healthy
  # zipkin:
  #   image: hiteshjoshi1/microservice-docker-cart-example
  #   container_name: zipkin
  #   ports:
  #    - "9411:9411"
  #   networks:
  #     - microservicesnet
  #   volumes:
  #     - ${HOME}/jarloc:/data
  #   command: -jar -Dspring.profiles.active=docker /data/zipkinTimer-0.0.1-SNAPSHOT.jar
  #   depends_on:
  #      config:
  #        condition: service_healthy              
         


networks:
  microservicesnet:
