#notice the use of profiles one for localhost, one for docker
spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"  
  freemarker:
    enabled: false           # Ignore Eureka dashboard FreeMarker templates
#  zipkin:
#     locator:
#      discovery:
#        enabled: true
#     service:
#         name: inventory   
eureka: 
   instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION
    preferIpAddress: true    
    
server:
  port: ${inventory.port}      
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/microservices_prod
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: none    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${inventory.discovery.port}/eureka/     
  
---

spring:
  profiles: docker
  datasource:   #docker instance of mysql
    url: jdbc:mysql://localhost:32768/microservices_prod  
    username: root
    password: test
  jpa:
    hibernate:
      ddl-auto: none 
      naming:
       strategy: org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5Dialect
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:${inventory.discovery.port}/eureka/     # using eureka instead of localhost
    